language: erlang
sudo: false
install: true
before_script:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod +x rebar3
env: PATH=".:$PATH"
script: make check
otp_release:
  - 20.1
  - 19.3
